#!/bin/bash

MICRONETS_OP_SERVICE_DIR=/opt/micronets-onboard-proxy/service


function hr {
  echo "------------------------------------------------------------------------------------------------------"
}

function install-onboard-proxy-service {
  pushd ${MICRONETS_OP_SERVICE_DIR} > /dev/null
    # Ensure system service knows where to find node
    rm -rf bin
    mkdir bin
    ln -s `which node` bin/node
  popd > /dev/null

  echo "Installing micronets-onboard-proxy service."
  mv ${MICRONETS_OP_SERVICE_DIR}/micronets-onboard-proxy.service /lib/systemd/system > /dev/null 2>&1
  echo "Reloading service files."
  systemctl daemon-reload
  echo "Enabling micronets-onboard-proxy service."
  systemctl enable micronets-onboard-proxy.service
  echo "Starting micronets-onboard-proxy service."
  systemctl start micronets-onboard-proxy.service
}

function main {
  {
    echo "POSTINSTALL: ${TAG}"
    install-onboard-proxy-service
  } 2>&1 | logger -t ${TAG}
}

TS=`date +%j'T'%H%M%S`
TAG="mnop-post-${TS}"
if [ ! -z "${2}" ]; then
  echo "Upgrading from version ${2}"
fi
main
grep "${TAG}" /var/log/syslog
exit 0

