#!/bin/bash

function hr {
  echo "------------------------------------------------------------------------------------------------------"
}

function main {
  {
     echo "PRERM: ${TAG}"
     echo "Stopping micronets-onboard-proxy service."
     systemctl stop micronets-onboard-proxy.service
  } 2>&1 | logger -t ${TAG}
}

TS=`date +%j'T'%H%M%S`
TAG="mnop-pre-${TS}"
main
grep "${TAG}" /var/log/syslog
exit 0

